# Generated by Django 5.2.7 on 2025-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('system', 'System')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_from_user',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.CharField(max_length=20),
        ),
    ]
